### ISSUE TITLE
border-width and X-extent

### ISSUE THREAD

**Issue by uliska** [openlilylib/analysis#4]
I think the "reference point" should be the transition between fill and border. That also means the explicitly passed Y coordinate should refer to the *inner* edge of the border. So when `border-width` increases the border frame should grow to all four directions.

**Comment by KlausBlum** [comment]
That sounds absolutely reasonable to me. 
However, l-zigzag-width and r-zigzag-width must be a divisor of the respective Y extents (which would now be increased by 2*border-width). 

A solution would be to round the zigzag parameters to the nearest sensible value (e.g. in the original "leftZZspan" function).
