### ISSUE TITLE
Add frame-angle property

### ISSUE THREAD

**Issue by uliska** [openlilylib/analysis#6]
Needed to produce rotated frames. Unfortunately first test didn't properly work out.

**Comment by KlausBlum** [comment]
Not a big thing. Created new branch "frame-angle" which should implement this ability. 
Still untested as I cannot (yet?) compile OLL projects...

**Comment by KlausBlum** [comment]
Obviously that didn't work just out of the box. This branch is obsolete and will be deleted. 

Now there is a new branch "apply_frame-angle" where this is implemented and tested.

**Comment by KlausBlum** [comment]
Merged 21.06.2020
Frames now have an "angle" property.
